version: '3.4'

services:
  elasticsearch:
    image: elasticsearch:7.1.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - discovery.type=single-node
